//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类Wj_Code。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Wj_Code")]
    [Serializable]
    public partial class Wj_Code : Entity
    {
        #region Model
        private string _Code;
        private string _Url;

        /// <summary>
        /// 
        /// </summary>
        [Field("Code")]
        public string Code
        {
            get { return _Code; }
            set
            {
                this.OnPropertyValueChange("Code");
                this._Code = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Url")]
        public string Url
        {
            get { return _Url; }
            set
            {
                this.OnPropertyValueChange("Url");
                this._Url = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Code,
				_.Url,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Code,
				this._Url,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Wj_Code");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Code = new Field("Code", "Wj_Code", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Url = new Field("Url", "Wj_Code", "");
        }
        #endregion
    }
}