//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类WJ_GoodsName。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("WJ_GoodsName")]
    [Serializable]
    public partial class WJ_GoodsName : Entity
    {
        #region Model
        private long _CustomerID;
        private string _GoodsCode;
        private string _GoodsName;

        /// <summary>
        /// 
        /// </summary>
        [Field("CustomerID")]
        public long CustomerID
        {
            get { return _CustomerID; }
            set
            {
                this.OnPropertyValueChange("CustomerID");
                this._CustomerID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("GoodsCode")]
        public string GoodsCode
        {
            get { return _GoodsCode; }
            set
            {
                this.OnPropertyValueChange("GoodsCode");
                this._GoodsCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("GoodsName")]
        public string GoodsName
        {
            get { return _GoodsName; }
            set
            {
                this.OnPropertyValueChange("GoodsName");
                this._GoodsName = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.CustomerID,
				_.GoodsCode,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.CustomerID,
				_.GoodsCode,
				_.GoodsName,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._CustomerID,
				this._GoodsCode,
				this._GoodsName,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "WJ_GoodsName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CustomerID = new Field("CustomerID", "WJ_GoodsName", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field GoodsCode = new Field("GoodsCode", "WJ_GoodsName", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field GoodsName = new Field("GoodsName", "WJ_GoodsName", "");
        }
        #endregion
    }
}