//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类WJ_Photo。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("WJ_Photo")]
    [Serializable]
    public partial class WJ_Photo : Entity
    {
        #region Model
        private long _CustomerID;
        private string _WJID;
        private string _PhotoID;
        private string _PhotoPath;
        private DateTime _AtTime;

        /// <summary>
        /// 客户ID
        /// </summary>
        [Field("CustomerID")]
        public long CustomerID
        {
            get { return _CustomerID; }
            set
            {
                this.OnPropertyValueChange("CustomerID");
                this._CustomerID = value;
            }
        }
        /// <summary>
        /// 挖机编号
        /// </summary>
        [Field("WJID")]
        public string WJID
        {
            get { return _WJID; }
            set
            {
                this.OnPropertyValueChange("WJID");
                this._WJID = value;
            }
        }
        /// <summary>
        /// 图片编号 格式: [客户编号_挖机编号_时间(YYMMddHHmmss)]
        /// </summary>
        [Field("PhotoID")]
        public string PhotoID
        {
            get { return _PhotoID; }
            set
            {
                this.OnPropertyValueChange("PhotoID");
                this._PhotoID = value;
            }
        }
        /// <summary>
        /// 图片路径 文件格式： PhotoID.扩展名
        /// </summary>
        [Field("PhotoPath")]
        public string PhotoPath
        {
            get { return _PhotoPath; }
            set
            {
                this.OnPropertyValueChange("PhotoPath");
                this._PhotoPath = value;
            }
        }
        /// <summary>
        /// 抓拍时间
        /// </summary>
        [Field("AtTime")]
        public DateTime AtTime
        {
            get { return _AtTime; }
            set
            {
                this.OnPropertyValueChange("AtTime");
                this._AtTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.CustomerID,
				_.WJID,
				_.PhotoID,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.CustomerID,
				_.WJID,
				_.PhotoID,
				_.PhotoPath,
				_.AtTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._CustomerID,
				this._WJID,
				this._PhotoID,
				this._PhotoPath,
				this._AtTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "WJ_Photo");
            /// <summary>
            /// 客户ID
            /// </summary>
            public readonly static Field CustomerID = new Field("CustomerID", "WJ_Photo", "客户ID");
            /// <summary>
            /// 挖机编号
            /// </summary>
            public readonly static Field WJID = new Field("WJID", "WJ_Photo", "挖机编号");
            /// <summary>
            /// 图片编号 格式: [客户编号_挖机编号_时间(YYMMddHHmmss)]
            /// </summary>
            public readonly static Field PhotoID = new Field("PhotoID", "WJ_Photo", "图片编号 格式: [客户编号_挖机编号_时间(YYMMddHHmmss)]");
            /// <summary>
            /// 图片路径 文件格式： PhotoID.扩展名
            /// </summary>
            public readonly static Field PhotoPath = new Field("PhotoPath", "WJ_Photo", "图片路径 文件格式： PhotoID.扩展名");
            /// <summary>
            /// 抓拍时间
            /// </summary>
            public readonly static Field AtTime = new Field("AtTime", "WJ_Photo", "抓拍时间");
        }
        #endregion
    }
}