//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类WJ_Record_Submit。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("WJ_Record_Submit")]
    [Serializable]
    public partial class WJ_Record_Submit : Entity
    {
        #region Model
        private long _SeqID;
        private long _CustomerID;
        private string _WJID;
        private long _ID;
        private string _WorkSpace;
        private string _GoodsName;
        private DateTime _BeginTime;
        private DateTime? _EndTime;
        private string _BeginPhotoID;
        private string _EndPhotoID;
        private float _longitude;
        private float _Latitude;
        private int _Mode;
        private string _TruckID;
        private int _State;

        /// <summary>
        /// 自增字段（用于传输）
        /// </summary>
        [Field("SeqID")]
        public long SeqID
        {
            get { return _SeqID; }
            set
            {
                this.OnPropertyValueChange("SeqID");
                this._SeqID = value;
            }
        }
        /// <summary>
        /// 客户ID
        /// </summary>
        [Field("CustomerID")]
        public long CustomerID
        {
            get { return _CustomerID; }
            set
            {
                this.OnPropertyValueChange("CustomerID");
                this._CustomerID = value;
            }
        }
        /// <summary>
        /// 挖机编号
        /// </summary>
        [Field("WJID")]
        public string WJID
        {
            get { return _WJID; }
            set
            {
                this.OnPropertyValueChange("WJID");
                this._WJID = value;
            }
        }
        /// <summary>
        /// ID, 取时间戳
        /// </summary>
        [Field("ID")]
        public long ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 作业地点
        /// </summary>
        [Field("WorkSpace")]
        public string WorkSpace
        {
            get { return _WorkSpace; }
            set
            {
                this.OnPropertyValueChange("WorkSpace");
                this._WorkSpace = value;
            }
        }
        /// <summary>
        /// 物料类型
        /// </summary>
        [Field("GoodsName")]
        public string GoodsName
        {
            get { return _GoodsName; }
            set
            {
                this.OnPropertyValueChange("GoodsName");
                this._GoodsName = value;
            }
        }
        /// <summary>
        /// 起始时间
        /// </summary>
        [Field("BeginTime")]
        public DateTime BeginTime
        {
            get { return _BeginTime; }
            set
            {
                this.OnPropertyValueChange("BeginTime");
                this._BeginTime = value;
            }
        }
        /// <summary>
        /// 结束时间
        /// </summary>
        [Field("EndTime")]
        public DateTime? EndTime
        {
            get { return _EndTime; }
            set
            {
                this.OnPropertyValueChange("EndTime");
                this._EndTime = value;
            }
        }
        /// <summary>
        /// 开始图片ID
        /// </summary>
        [Field("BeginPhotoID")]
        public string BeginPhotoID
        {
            get { return _BeginPhotoID; }
            set
            {
                this.OnPropertyValueChange("BeginPhotoID");
                this._BeginPhotoID = value;
            }
        }
        /// <summary>
        /// 结束图片ID
        /// </summary>
        [Field("EndPhotoID")]
        public string EndPhotoID
        {
            get { return _EndPhotoID; }
            set
            {
                this.OnPropertyValueChange("EndPhotoID");
                this._EndPhotoID = value;
            }
        }
        /// <summary>
        /// GPS精度
        /// </summary>
        [Field("longitude")]
        public float longitude
        {
            get { return _longitude; }
            set
            {
                this.OnPropertyValueChange("longitude");
                this._longitude = value;
            }
        }
        /// <summary>
        /// GPS维度
        /// </summary>
        [Field("Latitude")]
        public float Latitude
        {
            get { return _Latitude; }
            set
            {
                this.OnPropertyValueChange("Latitude");
                this._Latitude = value;
            }
        }
        /// <summary>
        /// 数据类型； 0:表示 计次； 1：表示计时
        /// </summary>
        [Field("Mode")]
        public int Mode
        {
            get { return _Mode; }
            set
            {
                this.OnPropertyValueChange("Mode");
                this._Mode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TruckID")]
        public string TruckID
        {
            get { return _TruckID; }
            set
            {
                this.OnPropertyValueChange("TruckID");
                this._TruckID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("State")]
        public int State
        {
            get { return _State; }
            set
            {
                this.OnPropertyValueChange("State");
                this._State = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.SeqID,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.SeqID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.SeqID,
				_.CustomerID,
				_.WJID,
				_.ID,
				_.WorkSpace,
				_.GoodsName,
				_.BeginTime,
				_.EndTime,
				_.BeginPhotoID,
				_.EndPhotoID,
				_.longitude,
				_.Latitude,
				_.Mode,
				_.TruckID,
				_.State,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._SeqID,
				this._CustomerID,
				this._WJID,
				this._ID,
				this._WorkSpace,
				this._GoodsName,
				this._BeginTime,
				this._EndTime,
				this._BeginPhotoID,
				this._EndPhotoID,
				this._longitude,
				this._Latitude,
				this._Mode,
				this._TruckID,
				this._State,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "WJ_Record_Submit");
            /// <summary>
            /// 自增字段（用于传输）
            /// </summary>
            public readonly static Field SeqID = new Field("SeqID", "WJ_Record_Submit", "自增字段（用于传输）");
            /// <summary>
            /// 客户ID
            /// </summary>
            public readonly static Field CustomerID = new Field("CustomerID", "WJ_Record_Submit", "客户ID");
            /// <summary>
            /// 挖机编号
            /// </summary>
            public readonly static Field WJID = new Field("WJID", "WJ_Record_Submit", "挖机编号");
            /// <summary>
            /// ID, 取时间戳
            /// </summary>
            public readonly static Field ID = new Field("ID", "WJ_Record_Submit", "ID, 取时间戳");
            /// <summary>
            /// 作业地点
            /// </summary>
            public readonly static Field WorkSpace = new Field("WorkSpace", "WJ_Record_Submit", "作业地点");
            /// <summary>
            /// 物料类型
            /// </summary>
            public readonly static Field GoodsName = new Field("GoodsName", "WJ_Record_Submit", "物料类型");
            /// <summary>
            /// 起始时间
            /// </summary>
            public readonly static Field BeginTime = new Field("BeginTime", "WJ_Record_Submit", "起始时间");
            /// <summary>
            /// 结束时间
            /// </summary>
            public readonly static Field EndTime = new Field("EndTime", "WJ_Record_Submit", "结束时间");
            /// <summary>
            /// 开始图片ID
            /// </summary>
            public readonly static Field BeginPhotoID = new Field("BeginPhotoID", "WJ_Record_Submit", "开始图片ID");
            /// <summary>
            /// 结束图片ID
            /// </summary>
            public readonly static Field EndPhotoID = new Field("EndPhotoID", "WJ_Record_Submit", "结束图片ID");
            /// <summary>
            /// GPS精度
            /// </summary>
            public readonly static Field longitude = new Field("longitude", "WJ_Record_Submit", "GPS精度");
            /// <summary>
            /// GPS维度
            /// </summary>
            public readonly static Field Latitude = new Field("Latitude", "WJ_Record_Submit", "GPS维度");
            /// <summary>
            /// 数据类型； 0:表示 计次； 1：表示计时
            /// </summary>
            public readonly static Field Mode = new Field("Mode", "WJ_Record_Submit", "数据类型； 0:表示 计次； 1：表示计时");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field TruckID = new Field("TruckID", "WJ_Record_Submit", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field State = new Field("State", "WJ_Record_Submit", "");
        }
        #endregion
    }
}